### ISSUE TITLE
Site description should reference NBIS

### ISSUE THREAD

**Issue by viklund** [NBISweden/mimir#22]
When linking to mimir in slack for example the autogenerated preview now links to "woongsang" and mentions "Nuxt PWA". We should instead use fields relevant for nbis. After mucking about a bit I think these `meta` tags need to be set in the html head element.

```
<meta name="description" content="NBIS ChatGPT interface">
<meta property="og:site_name" content="Mimir">
<meta property="og:description" content="NBIS ChatGPT interface"">
```

(and all other such references in the html).

**Comment by jonandernovella** [comment]
It seems the underlaying Nuxt PWA package has some interesting defaults:

https://github.com/kevinmarrec/nuxt-pwa-module/blob/a7263a2d7c39b1c5a60623c848fe2735e709be1f/src/module.ts#L35
