### ISSUE TITLE
feat: Implement rate limiting

### ISSUE THREAD

**Issue by jonandernovella** [NBISweden/mimir#7]
## Please describe the feature

As a Mimir maintainer, I want to make sure that users' have reasonable limits over how many tokens they can request from ChatGPT.

## Detailed description

- [ ] This limits could be enforced in different ways:
    - API key "K" can generate N tokens
    - User Account "U" can generate N tokens
    - IP address "A" can generate N tokens
    
The number of tokens "N" needs some research before we find a good number. AFAIK the maximum tokens per conversation is 4096. So if we want to allow a maximum 20 conversations per day, perhaps 20*4096 could be a good starting point?

To read more about rate limiting: https://platform.openai.com/docs/guides/rate-limits/overview

## Acceptance criteria
- [ ] Clients who have used more than N tokens should be stopped from starting conversations with Mimir
- [ ] Integration tests should be implemented so that we make sure the limits are correctly in place

**Comment by jhagberg** [comment]
no fix
